<definitions targetNamespace='http://reliance.com/wsdl' name='WSDLInterface' xmlns='http://schemas.xmlsoap.org/wsdl/' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' xmlns:tns='http://reliance.com/wsdl' xmlns:tsarenquiryreqbo='http://reliance.com/schema'>
  <types>
    <xsd:schema targetNamespace='http://reliance.com/wsdl' attributeFormDefault='unqualified' elementFormDefault='unqualified' xmlns:xsd='http://www.w3.org/2001/XMLSchema'>
      <xsd:import namespace='http://reliance.com/schema' schemaLocation='tsarEnquiryResBO.xsd' />
      <xsd:import namespace='http://reliance.com/schema' schemaLocation='tsarEnquiryReqBO.xsd' />
      <xsd:element name='tsarEnquiry'>
        <xsd:complexType>
          <xsd:sequence minOccurs='1' maxOccurs='1'>
            <xsd:element ref='tsarenquiryreqbo:tsarEnquiryReqBO' />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name='tsarEnquiryResponse'>
        <xsd:complexType>
          <xsd:sequence minOccurs='1' maxOccurs='1'>
            <xsd:element ref='tsarenquiryreqbo:tsarEnquiryResBO' />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </types>
  <message name='tsarEnquiry'>
    <part name='parameters' element='tns:tsarEnquiry' xmlns:tns='http://reliance.com/wsdl' />
  </message>
  <message name='tsarEnquiryResponse'>
    <part name='parameters' element='tns:tsarEnquiryResponse' xmlns:tns='http://reliance.com/wsdl' />
  </message>
  <portType name='WSDLInterface'>
    <operation name='tsarEnquiry'>
      <input message='tns:tsarEnquiry' name='tsarEnquiry' />
      <output message='tns:tsarEnquiryResponse' name='tsarEnquiryResponse' />
    </operation>
  </portType>
</definitions>